name: Reveal
on:
  workflow_dispatch:
  schedule:
    # Run every day at 1:00 UTC
    - cron: '0 1 * * *'

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    
    - name: Checkout uma-bot repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        path: uma-bot
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # - name: Checkout uma-answers repo
    #   uses: actions/checkout@v4
    #   with:
    #     repository: lancelot-c/uma-answers
    #     ref: answers # branch
    #     path: uma-answers
    #     token: ${{ secrets.GH_ACCESS_TOKEN }}


    - name: Install dependencies # because isRevealPhase needs viem
      run: cd uma-bot && npm install
    - name: Install tsx globally to run ts files independently
      run: npm i -g tsx

    # Notify the UMA.rocks team if anything needs to be done today
    - name: Check if we need to provide answers today & if new unsupported price identifiers are detected
      continue-on-error: true # Make sure we continue the job if this script fails
      run: cd uma-bot && tsx ./smart-contract-calls/shouldIWorkToday.ts
      env:
        RPC_URL: ${{ secrets.RPC_URL }}
        DISCORD_CHANNEL_DEV_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_DEV_WEBHOOK_URL }}
        DISCORD_CHANNEL_HISTORY_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_HISTORY_WEBHOOK_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }} 



    - name: Pushes answers.json file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_ACCESS_TOKEN }}
      with:
        source_file: './uma-bot/test-data/answers.json'
        destination_repo: 'lancelot-c/uma-answers'
        destination_branch: 'answers'
        user_email: 'lancelot-c@users.noreply.github.com'
        user_name: 'uma-bot'
        commit_message: 'Fresh answers.json for the new voting round'


    # - name: Commit and push changes (if any)
    #   shell: bash
    #   env:
    #     CI_COMMIT_MESSAGE: update answers.json
    #     CI_COMMIT_AUTHOR: github-actions[bot]
    #     CI_COMMIT_EMAIL: lancelot-c@users.noreply.github.com
    #   run: |
    #     cd uma-answers
    #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
    #     git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
    #     if [[ `git status` ]]; then
    #         # Changes
    #         git add test-data/answers.json
    #         git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
    #         git push
    #     else
    #         # No changes
    #         echo "no changes to answers.json"
    #         exit 0
    #     fi

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v7
    #   with:
    #     token: ${{ secrets.UMA_ANSWERS_REPO_ACCESS_TOKEN }}
    #     title: 'Answers for voting round X'
    #     body: 'Conversation for voting round X'
    #     branch: 'main'
    #     base: 'main'
    #     draft: false
    #     add-paths: |
    #         test-data/answers.json


    # - name: Cancel job if not reveal phase
    #   continue-on-error: false # Make sure we stop the job if this script fails
    #   run: tsx ./uma-bot/smart-contract-calls/isRevealPhase.ts
    #   env:
    #     RPC_URL: ${{ secrets.RPC_URL }}
    #     ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}     

    #V2
    # - name: Reveal V2
    #   continue-on-error: true
    #   run: tsx ./uma-bot/smart-contract-calls/reveal.ts
    #   env:
    #     PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
    #     RPC_URL: ${{ secrets.RPC_URL }}
    #     UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
    #     UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
    #     DISCORD_CHANNEL_DEV_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_DEV_WEBHOOK_URL }}
    #     ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}


    # - name: Post summary on Discord
    #   continue-on-error: true # See https://stackoverflow.com/a/70048004
    #   run: tsx ./uma-bot/smart-contract-calls/summary.ts
    #   env: # Set the secret as an environment variable
    #     PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
    #     RPC_URL: ${{ secrets.RPC_URL }}
    #     UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
    #     UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
    #     DISCORD_CHANNEL_GENERAL_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_GENERAL_WEBHOOK_URL }}
    #     DISCORD_CHANNEL_HISTORY_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_HISTORY_WEBHOOK_URL }}
    #     DISCORD_CHANNEL_DEV_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_DEV_WEBHOOK_URL }}
    #     ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }} 



    # - uses: stefanzweifel/git-auto-commit-action@v5  # Commit all changed files back to the repository
    #   with:
    #     # Optional. Commit message for the created commit.
    #     # Defaults to "Apply automatic changes"
    #     repository: ./uma-bot
    #     commit_message: Automated report
