name: Reveal
on:
  workflow_dispatch:
  schedule:
    # Run every day at 1:00 UTC
    - cron: '0 1 * * *'

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*


    - name: Install dependencies # because isRevealPhase needs viem
      run: npm install
    - name: Install tsx globally to run ts files independently
      run: npm i -g tsx

    # Notify the UMA.rocks team if anything needs to be done today
    - name: Check if we need to provide answers today & if new unsupported price identifiers are detected
      continue-on-error: true # Make sure we continue the job if this script fails
      run: tsx smart-contract-calls/shouldIWorkToday.ts
      env:
        RPC_URL: ${{ secrets.RPC_URL }}
        DISCORD_CHANNEL_DEV_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_DEV_WEBHOOK_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }} 

    - name: Cancel job if not reveal phase
      continue-on-error: false # Make sure we stop the job if this script fails
      run: tsx smart-contract-calls/isRevealPhase.ts
      env:
        RPC_URL: ${{ secrets.RPC_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}     

    #V2
    - name: Reveal V2
      continue-on-error: true
      run: tsx smart-contract-calls/reveal.ts
      env:
        PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
        RPC_URL: ${{ secrets.RPC_URL }}
        UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
        UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
        DISCORD_CHANNEL_DEV_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_DEV_WEBHOOK_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}


    - name: Post summary on Discord
      continue-on-error: true # See https://stackoverflow.com/a/70048004
      run: tsx smart-contract-calls/summary.ts
      env: # Set the secret as an environment variable
        PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
        RPC_URL: ${{ secrets.RPC_URL }}
        UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
        UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
        DISCORD_CHANNEL_GENERAL_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_GENERAL_WEBHOOK_URL }}
        DISCORD_CHANNEL_HISTORY_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_HISTORY_WEBHOOK_URL }}
        DISCORD_CHANNEL_DEV_WEBHOOK_URL: ${{ secrets.DISCORD_CHANNEL_DEV_WEBHOOK_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }} 

    - uses: stefanzweifel/git-auto-commit-action@v5  # Commit all changed files back to the repository
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Automated report
